import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../src/components/navbar'
import Dash from '../src/components/Dash'
import Foot from '../src/components/Foot'

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar />
      <div className={styles.container_dash}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
          <Dash />
          <Foot />
        </div>

      </div>

    </div>
  )
}
