import styles from '../styles/Home.module.css'
import Navbar from '../src/components/Navbar'
import Dash from '../src/components/Dash'
import Head from 'next/dist/shared/lib/head'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Dash />
    </div>
  )
}
